server:
  port: 8081

spring:
  application:
    name: gateway
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: admin



